version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672


  orchestrator:
    image: orchestrator:latest
    container_name: orchestrator
    build: orchestrator
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - rabbitmq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - mongo

  master:
    image: master:latest
    container_name: master
    build: master
    depends_on:
      - orchestrator
      - rabbitmq
    links:
      - mongo
    
  slave:
    image: slave:latest
    container_name: slave
    build: slave
    depends_on:
      - orchestrator
      - rabbitmq
    links:
      - mongo
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

